plugins {
    alias(libs.plugins.androidApplication)
}

android {
    namespace = "com.example.blackpearl"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.blackpearl"
        minSdk = 29
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
        // 确保包含 Java 代码
        multiDexEnabled true
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            //noinspection ChromeOsAbiSupport
            abiFilters 'arm64-v8a'
            //abiFilters "armeabi-v7a"
        }
        externalNativeBuild {
            cmake {
                cppFlags "-g"
                arguments "-DANDROID_STL=c++_shared"
            }
        }
    }
    splits {
        abi {
            enable false // 确保不启用ABI分包
        }
    }
    buildTypes {
        release {
            debuggable true
            jniDebuggable true
            minifyEnabled false
        }

        /*  release {
              minifyEnabled false
              proguardFiles(
                  getDefaultProguardFile("proguard-android-optimize.txt"),
                  "proguard-rules.pro"
              )
          }*/
        debug {
            debuggable true
            jniDebuggable true
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {

            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }

    sourceSets {
        main {
            //jniLibs.srcDirs = ['libs']
            jniLibs.srcDir 'lib/arm64-v8a/'

        }
    }

    packagingOptions {
        pickFirst 'lib/arm64-v8a/libassimpd.so'
        pickFirst 'lib/arm64-v8a/libSandBoxAndriod.so'
    }


    buildFeatures {
        viewBinding = true
    }
    ndkVersion '25.1.8937393'

}

dependencies {
    implementation libs.startup.runtime
    implementation libs.work.runtime
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.constraintlayout)
    testImplementation(libs.junit)
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
    implementation(libs.multidex)



}